DIRECTORIES:
  data: data
  stop_words: stop_words
  cleared_files: cleared_files
  valid_files: validated_files
  cluster_exec_reports: cluster_exec_reports
  detailed_cluster_exec_reports: detailed_cluster_exec_reports
  detailed_filtered_reports: detailed_filtered_reports
  comparing_reports: comparing_reports
  empty_content: empty_content
  tmp: tmp
  embeddings: embeddings
  faiss_vectors: faiss_vectors
  current_df: current_df
  filtered_df: filtered_df
  swearwords_dir: swear_words
  allowed_reports_formats: allowed_reports_formats

FILES:
  embedded_json: embeddings.json
  rows_cardinalities: rows_cardinalities.json
  current_df: current_df.parquet.gzip
  filtered_df: filtered_df.parquet.gzip
  polish_swearwords: 'polish_swearwords.txt'
  english_swearwords: 'english_swearwords.txt'
  topics_df: topics_df.csv
  ext_mappings: mimetypes_formats.json

INPUT_FILES_SETTINGS:
  allowed_extensions:
    - .csv 
    - .txt
    - .xlsx
  required_columns: 
    - Questioned_Date
    - Model_No
    - OS
    - SW_Version 
    - CSC
    - Category 
    - Application_Name
    - content

ETL_SETTINGS:
  translate: true
  sentiment: true

REPORT_SETTINGS:
  original_content_column: content
  preprocessed_content_column: preprocessed_content
  labels_column: labels
  cardinalities_column: counts
  sentiment_column: sentiment
  filename_column: filename
  base_columns:
    - Questioned_Date
    - Model_No
    - OS
    - SW_Version 
    - CSC
    - Category 
    - Application_Name

  topic_column_prefix: Word
  no_topic_token: '-'
  comparing_report_suffix: _comparison
  cluster_exec_filename_prefix: cluster_exec
  detailed_cluster_exec_filename_prefix: detailed
  cluster_exec_filename_ext: .parquet.gzip
  filtered_filename_prefix: filtered
  filtered_filename_ext: .parquet.gzip

  cols_for_label: ['New_Word_1', 'New_Word_2', 'New_Word_3', 'New_Word_4', 'New_Word_5']
  cols_for_old_label: ['Old_Word_1', 'Old_Word_2', 'Old_Word_3', 'Old_Word_4', 'Old_Word_5']
  no_topic_phrase: '<NO_TOPIC>'
  indicator_col: 'Comparison'
  new_group_value: 'New group'
  old_group_value: 'Old group'
  new_group_col_name: 'New_counts'
  old_group_col_name: 'Old_counts'
  new_group_plot_title: 'New groups counts'
  old_group_plot_title: 'Old groups counts'

LOGGER:
  logging_format: '[%(asctime)s] - %(levelname)s - %(message)s'
  logger_level: DEBUG

EMPTY_CONTENT_SETTINGS:
  empty_content_suffix: _EMPTY_CONTENT
  empty_content_ext: .csv

PIPELINE:
  content_column: content
  batch_size: 16
  cleared_file_ext: .csv

ML:
  seed: 42
  recalculate_clusters_treshold: 0.1
  embeddings:
    model_name: sentence-transformers/all-mpnet-base-v2
  UMAP:
    dim_reducer_model_name: 'umap_reducer.pkl'
    reducer_2d_model_name: 'dim_reducer_2d.pkl'
    n_neighbors: 15
    min_dist: 0.0
    n_components: 5
  topics:
    - 2
  sentiment:
    model_name: 'cardiffnlp/twitter-xlm-roberta-base-sentiment-multilingual'
    
  HDBSCAN_SETTINGS:
    model_name: 'clusterer.pkl'
    min_cluster_size: 15
    min_samples: 15
    outlier_treshold: 0.1
    metric: euclidean                      
    cluster_selection_method: eom

  translation_models:
    pl: Helsinki-NLP/opus-mt-pl-en
    de: Helsinki-NLP/opus-mt-de-en
    es: Helsinki-NLP/opus-mt-es-en
    ko: Helsinki-NLP/opus-mt-ko-en

  lang_detection_model: papluca/xlm-roberta-base-language-detection

FILTERING:
  
